package com.clinic.entity;

public enum NotificationType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_ACCEPTED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_COMPLETED,
    PRESCRIPTION_CREATED,
    ACCESS_REQUEST_CREATED,
    ACCESS_REQUEST_APPROVED,
    ACCESS_REQUEST_REJECTED
}
